version: "3.9"

services:
  dedicated-server:
    build: .
    container_name: dedicated-server
    restart: always
    network_mode: host
    environment:
      APP_ID: 1948160
      APP_INSTALL_DIR: /dedicated-server
    volumes:
      - steamcmd-volume:/root/.steam
      - dedicated-server-volume:/dedicated-server
    command:
      - /bin/bash
      - -c
      - "while true; do sleep 1000; done"

volumes:
  steamcmd-volume:
  dedicated-server-volume:
