version: "3.9"

services:
  dedicated-server:
    build: .
    container_name: dedicated-server
    restart: always
    network_mode: host
    environment:
      APP_ID: 1948160
    volumes:
      - ./data:/data
    command:
      - /bin/bash
