version: "3.9"

services:
  dstserver:
    build: .
    container_name: dstserver
    restart: always
    network_mode: host
    environment:
      APP_ID: 343050
      APP_INSTALL_DIR: /dstserver
    volumes:
      - steamcmd-volume:/root/.steam
      - dstserver-volume:/dstserver
      - ./start_server.sh:/start_server.sh
      - ./Cluster_1:/root/.klei/DoNotStarveTogether/Cluster_1
    working_dir: /dstserver/bin
    command:
      - /start_server.sh

volumes:
  steamcmd-volume:
  dstserver-volume:
