version: "3.9"

services:
  l4d2:
    build: .
    container_name: l4d2
    restart: always
    network_mode: host
    environment:
      APP_ID: 222860
      APP_INSTALL_DIR: /l4d2
      UPDATE: if_not_exist
    volumes:
      - steamcmd-volume:/root/.steam
      - l4d2-volume:/l4d2
      - ./start_server.sh:/start_server.sh
      - ./server.cfg:/server.cfg
    working_dir: /l4d2
    command:
      - /start_server.sh

volumes:
  steamcmd-volume:
  l4d2-volume:
